"use client";

import { useState, useEffect } from "react";
import { Brain, Lightbulb, RefreshCw, TrendingUp, AlertTriangle, Package, BarChart3 } from "lucide-react";
import { retailerService } from "@/services/retailerService";
import type { AIInsight } from "@/types";

const iconMap: Record<string, React.ComponentType<{ className?: string }>> = {
  demand_spike: TrendingUp, waste_risk: AlertTriangle, stock_shortage: AlertTriangle, overstock: Package, fast_moving: BarChart3,
};

const colorMap: Record<string, string> = {
  demand_spike: "bg-slate-50 text-slate-500",
  waste_risk: "bg-red-50 text-red-600",
  stock_shortage: "bg-slate-50 text-slate-500",
  overstock: "bg-amber-50 text-amber-600",
  fast_moving: "bg-slate-50 text-slate-500",
};

const severityColor: Record<string, string> = {
  high: "border-l-red-500",
  medium: "border-l-amber-500",
  low: "border-l-green-500",
};

export default function RetailerInsights() {
  const [insights, setInsights] = useState<AIInsight[]>([]);
  const [loading, setLoading] = useState(true);

  const fetchInsights = async () => {
    setLoading(true);
    const res = await retailerService.getInsights();
    if (res.success && res.data) setInsights(res.data as AIInsight[]);
    setLoading(false);
  };

  useEffect(() => {
    async function loadInsights() {
      const res = await retailerService.getInsights();
      if (res.success && res.data) setInsights(res.data as AIInsight[]);
      setLoading(false);
    }
    loadInsights();
  }, []);

  const categoryCounts = [
    { label: "Demand", count: insights.filter(i => i.type === "demand_spike").length, color: "bg-slate-500" },
    { label: "Inventory", count: insights.filter(i => i.type === "stock_shortage" || i.type === "overstock").length, color: "bg-red-500" },
    { label: "Sales", count: insights.filter(i => i.type === "fast_moving").length, color: "bg-slate-500" },
    { label: "Waste", count: insights.filter(i => i.type === "waste_risk").length, color: "bg-slate-500" },
    { label: "Efficiency", count: 0, color: "bg-slate-500" },
    { label: "Forecast", count: insights.filter(i => i.type === "demand_spike").length, color: "bg-slate-500" },
  ];

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="p-3 bg-slate-100 rounded-lg"><Brain className="w-6 h-6 text-slate-500" /></div>
          <div><h1 className="text-2xl font-bold text-slate-800">AI Insights</h1><p className="text-slate-500">Intelligent business intelligence generated by AI</p></div>
        </div>
        <button onClick={fetchInsights} className="flex items-center gap-2 px-3 py-2 border border-slate-200 rounded-lg text-slate-500 hover:bg-slate-50"><RefreshCw className="w-4 h-4" />Refresh</button>
      </div>

      <div className="bg-white rounded-lg p-4 border border-slate-200 shadow-sm">
        <p className="text-sm text-slate-500"><span className="font-medium text-slate-700">AI Status: </span>{insights.length > 0 ? `${insights.length} insights generated from your data` : "Models are ready and will begin processing insights once store data is available."}</p>
      </div>

      <div className="space-y-4">
        {loading ? (
          <div className="bg-white rounded-lg p-12 text-center shadow-sm border border-slate-200"><p className="text-slate-400">Analyzing your data...</p></div>
        ) : insights.length === 0 ? (
          <div className="bg-white rounded-lg p-12 text-center shadow-sm border border-slate-200"><Lightbulb className="w-12 h-12 text-slate-300 mx-auto mb-4" /><h3 className="text-lg font-semibold text-slate-800">No Insights Yet</h3><p className="text-slate-500">Add inventory and sales data to generate AI-driven insights.</p></div>
        ) : insights.map((insight, i) => {
          const Icon = iconMap[insight.type] || Lightbulb;
          const colorClass = colorMap[insight.type] || "bg-slate-50 text-slate-600";
          return (
            <div key={i} className={`bg-white rounded-lg p-5 shadow-sm border border-slate-200 border-l-4 ${severityColor[insight.severity ?? "low"] || "border-l-emerald-500"}`}>
              <div className="flex items-start gap-4">
                <div className={`p-2 rounded-lg ${colorClass}`}><Icon className="w-5 h-5" /></div>
                <div className="flex-1">
                  <div className="flex items-center justify-between"><h4 className="font-semibold text-slate-800">{insight.title}</h4><span className={`px-2 py-0.5 rounded-full text-xs font-medium ${insight.severity === "high" ? "bg-red-100 text-red-700" : insight.severity === "medium" ? "bg-amber-100 text-amber-700" : "bg-slate-100 text-slate-700"}`}>{insight.severity ?? "low"}</span></div>
                  <p className="text-sm text-slate-600 mt-1">{insight.description}</p>
                  {insight.action && <p className="text-xs text-slate-400 mt-2">Recommended: {insight.action}</p>}
                </div>
              </div>
            </div>
          );
        })}
      </div>

      <div className="bg-white rounded-lg p-6 shadow-sm border border-slate-200">
        <h3 className="font-semibold text-slate-800 mb-4">Insight Categories</h3>
        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-6">
          {categoryCounts.map(cat => (
            <div key={cat.label} className="text-center p-4 bg-slate-50 rounded-lg"><div className={`w-3 h-3 rounded-full ${cat.color} mx-auto mb-2`} /><p className="text-2xl font-bold text-slate-800">{cat.count}</p><p className="text-sm text-slate-500">{cat.label} Insights</p></div>
          ))}
        </div>
      </div>
    </div>
  );
}
